package org.pragmatica.example.ticketing.booking;

import java.util.List;
import java.util.UUID;

import org.pragmatica.aether.pg.codegen.annotation.Query;
import org.pragmatica.aether.resource.db.PgSql;
import org.pragmatica.lang.Option;
import org.pragmatica.lang.Promise;
import org.pragmatica.lang.Unit;


/// Booking persistence (@PgSql), shared by every booking use-case slice. Single-statement,
/// validator-friendly SQL only -- no CTEs and no correlated subqueries (pg-codegen resolves a
/// subquery's scope independently of the enclosing statement, so an outer table is invisible inside
/// one).
///
/// The seat claim is the design-out serialization point: `seat_id` is the primary key, so there is
/// exactly one reservation row per seat, and it is reclaimed atomically by an `INSERT ... ON CONFLICT
/// (seat_id) DO UPDATE ... WHERE` guard. The guard admits a cancelled or expired reservation, a hold
/// whose TTL has passed, and the same customer's own live hold **within the total lifetime cap**
/// (which is how a hold becomes a purchase, without letting a timer-driven re-acquire hold the seat
/// forever -- see [#MAX_HOLD_MINUTES]); it never admits a confirmed sale or another customer's live
/// hold, so the losing buyer sees zero rows -> typed SeatUnavailable in the slice.
///
/// A claim's identity is `claim_id`, an ordinary NON-key column regenerated by the database on every
/// successful claim and returned by `claimSeat`. Slices carry the RETURNED value: it is the only
/// proof of which claim they own, and a concurrent reclaim rotates it, so every subsequent guarded
/// transition (`WHERE claim_id = :claimId`) fails closed rather than acting on somebody else's claim.
/// Because the key never changes, `bookings.reservation_claim_id` can record the claim a sale was
/// made under as a point-in-time fact with no foreign key, and re-selling a cancelled seat cannot
/// collide with the history of its previous sales.
///
/// Lifecycle transitions are guarded `UPDATE ... RETURNING claim_id`: an out-of-state row yields an
/// empty projection rather than silently mutating. Sale status and price are read synchronously from
/// the event-management and pricing slices, so this store keeps no local read projections.
@PgSql
public interface BookingStore {
    /// Decay boundary of one hold: every admitted claim, fresh or refresh, sets `expires_at` this far
    /// ahead. Mirrors the `interval '15 minutes'` literals in [#claimSeat] -- a `@Query` string is an
    /// annotation value and cannot interpolate a constant, so the two are changed together.
    long HOLD_TTL_MINUTES = 15;
    /// Total lifetime cap of a SINGLE hold, measured from its first claim (`held_since`) and NOT reset
    /// by a refresh: four full TTLs. Beyond it the claim guard refuses the owner's refresh, so a client
    /// re-acquiring on a timer can no longer squat a seat forever. Mirrors the `interval '60 minutes'`
    /// literal in [#claimSeat] (same annotation-constant caveat as [#HOLD_TTL_MINUTES]).
    ///
    /// The refusal is not instantaneous eviction: the squatter's outstanding hold stays live until its
    /// own `expires_at`, so the seat returns to contention within at most [#HOLD_TTL_MINUTES] more
    /// minutes -- through the expired branch of the guard or the hold sweep, whichever arrives first.
    long MAX_HOLD_MINUTES = 60;

    /// Identity of a single claim on a seat. Rotates on every successful claim, so it doubles as the
    /// optimistic-concurrency token for the guarded lifecycle transitions. Component order matches
    /// the RETURNING column order.
    record ClaimRef(UUID claimId, long version) {}

    /// Projection of a RETURNING id clause. Component order matches the RETURNING column order.
    record RowId(UUID id) {}

    /// A freed seat from a reaper sweep, carrying the version of the transition that freed it so the
    /// published fact can be ordered against other facts for the same seat. Component order matches
    /// the RETURNING column order.
    record SeatRef(UUID seatId, UUID eventId, long version) {}

    /// Current-state read of a booking. Component order matches the SELECT column order.
    record BookingRow(String status, UUID customerId, UUID seatId, UUID ticketId, UUID eventId) {}

    /// Hold decay snapshot: the persisted state plus time-as-decay flags computed at read. The flags
    /// describe a live hold only and are meaningless unless `state` is 'held' -- a reservation with
    /// no `expires_at` yields no decay at all (see the COALESCE in `holdDecay`).
    /// Component order matches the SELECT column order.
    record HoldRow(String state, boolean expired, boolean stale) {}

    /// A recorded refund receipt. Component order matches the SELECT column order.
    record ReceiptRef(UUID receiptId) {}

    /// Claim a seat, rotating the claim identity the database generates and returning it. An empty
    /// projection means the guard refused: the seat is confirmed to somebody, held by a different
    /// customer whose hold has not expired, or held by THIS customer for longer than
    /// [#MAX_HOLD_MINUTES] already.
    ///
    /// The guard's three branches are a reclaim (`cancelled`/`expired`), a lapsed hold, and the owner's
    /// own live hold -- the last one bounded, because it is the one that repeats. `held_since` is the
    /// start of the current hold's lifetime and is preserved by exactly that branch (the `CASE`: same
    /// customer, state `held`, not yet lapsed); every other admitted branch is a genuine reclaim and
    /// resets it to `now()`, so a seat that returns to contention always grants its next holder a full
    /// lifetime. `created_at` deliberately still moves on every claim: it dates the CURRENT claim, which
    /// is what [#expireOrphanedConfirmations] ages.
    @Query("""
           INSERT INTO reservations (seat_id, claim_id, event_id, customer_id, state, expires_at, created_at, held_since, version)
           VALUES (:seatId, gen_random_uuid(), :eventId, :customerId, 'held', now() + interval '15 minutes', now(), now(), 0)
           ON CONFLICT (seat_id) DO UPDATE SET claim_id = gen_random_uuid(), event_id = EXCLUDED.event_id,
           customer_id = EXCLUDED.customer_id, state = 'held', expires_at = EXCLUDED.expires_at,
           created_at = now(),
           held_since = CASE WHEN reservations.state = 'held' AND reservations.expires_at > now()
           AND reservations.customer_id = EXCLUDED.customer_id THEN reservations.held_since ELSE now() END,
           version = reservations.version + 1
           WHERE reservations.state IN ('cancelled', 'expired')
           OR (reservations.state = 'held' AND reservations.expires_at < now())
           OR (reservations.state = 'held' AND reservations.customer_id = EXCLUDED.customer_id
           AND reservations.held_since > now() - interval '60 minutes')
           RETURNING claim_id, version""")
    Promise<Option<ClaimRef>> claimSeat(UUID seatId, UUID eventId, UUID customerId);

    @Query("""
           UPDATE reservations SET state = 'confirmed', expires_at = NULL, version = version + 1
           WHERE claim_id = :claimId AND state = 'held' RETURNING claim_id, version""")
    Promise<Option<ClaimRef>> confirmReservation(UUID claimId);

    /// Release whatever this claim currently holds. Guarded by claim identity rather than by state:
    /// saga compensation must be able to release a reservation it has already confirmed, but must
    /// never release a claim that has since been rotated away from it.
    @Query("""
           UPDATE reservations SET state = 'cancelled', expires_at = NULL, version = version + 1
           WHERE claim_id = :claimId RETURNING claim_id, version""")
    Promise<Option<ClaimRef>> releaseReservation(UUID claimId);

    @Query("""
           UPDATE reservations SET state = 'cancelled', expires_at = NULL, version = version + 1
           WHERE seat_id = :seatId AND state = 'confirmed' RETURNING claim_id, version""")
    Promise<Option<ClaimRef>> cancelReservationBySeat(UUID seatId);

    @Query("SELECT count(*) FROM bookings WHERE customer_id = :customerId AND status = 'confirmed'")
    Promise<Long> activeBookingCount(UUID customerId);

    @Query("""
           INSERT INTO bookings (id, reservation_claim_id, seat_id, event_id, customer_id, status, ticket_id)
           VALUES (:id, :reservationClaimId, :seatId, :eventId, :customerId, 'confirmed', :ticketId)""")
    Promise<Unit> insertBooking(UUID id,
                                UUID reservationClaimId,
                                UUID seatId,
                                UUID eventId,
                                UUID customerId,
                                UUID ticketId);

    @Query("""
           INSERT INTO payments (id, booking_id, status, receipt_id, amount_minor, currency)
           VALUES (:id, :bookingId, :status, :receiptId, :amountMinor, :currency)""")
    Promise<Unit> insertPayment(UUID id,
                                UUID bookingId,
                                String status,
                                UUID receiptId,
                                long amountMinor,
                                String currency);

    @Query("""
           INSERT INTO tickets (id, booking_id, seat_id, status)
           VALUES (:id, :bookingId, :seatId, 'issued')""")
    Promise<Unit> insertTicket(UUID id, UUID bookingId, UUID seatId);

    @Query("SELECT status, customer_id, seat_id, ticket_id, event_id FROM bookings WHERE id = :id")
    Promise<Option<BookingRow>> findBooking(UUID id);

    @Query("UPDATE bookings SET status = 'cancelled' WHERE id = :id AND status = 'confirmed' RETURNING id")
    Promise<Option<RowId>> cancelBooking(UUID id);

    @Query("UPDATE tickets SET status = 'invalidated' WHERE id = :id")
    Promise<Unit> invalidateTicket(UUID id);

    /// The receipt of a refund already recorded for this booking, if any. This is the idempotency key
    /// of the cancellation: a re-driven cancel reads the receipt back instead of refunding twice.
    @Query("""
           SELECT receipt_id FROM payments
           WHERE booking_id = :bookingId AND status = 'refunded' AND receipt_id IS NOT NULL
           LIMIT 1""")
    Promise<Option<ReceiptRef>> findRefund(UUID bookingId);

    /// Record a completed refund against the booking's authorized payment. Guarded on 'authorized' so
    /// it can only ever move a payment forward once.
    @Query("""
           UPDATE payments SET status = 'refunded', receipt_id = :receiptId
           WHERE booking_id = :bookingId AND status = 'authorized'""")
    Promise<Unit> markRefunded(UUID receiptId, UUID bookingId);

    /// Decay snapshot for a seat. `expires_at` is NULL for every state except 'held', which makes
    /// both comparisons SQL NULL; COALESCE keeps them bindable to the primitive components of
    /// HoldRow, and the caller decides by `state` whether the flags mean anything.
    @Query("""
           SELECT state, COALESCE(expires_at < now(), FALSE) AS expired,
           COALESCE(expires_at < now() + interval '5 minutes', FALSE) AS stale
           FROM reservations WHERE seat_id = :seatId""")
    Promise<Option<HoldRow>> holdDecay(UUID seatId);

    @Query("""
           UPDATE reservations SET state = 'expired', version = version + 1
           WHERE state = 'held' AND expires_at < now() RETURNING seat_id, event_id, version""")
    Promise<List<SeatRef>> expireHolds();

    /// Reap confirmed reservations that never became a sale -- the crash window between
    /// `confirmReservation` and `insertBooking`, and a cancellation whose final booking write failed.
    /// No live process will ever free these, and the claim guard excludes 'confirmed', so without
    /// this the seat is lost forever. Bounded by claim age so it can never race a purchase in flight.
    /// `reservation_claim_id` is NOT NULL, so the NOT IN cannot be poisoned by a NULL.
    ///
    /// This must stay ONE statement: selecting the orphans and cancelling them separately would let a
    /// purchase write its booking row in between, and the reap would then cancel a live sale.
    /// pg-codegen resolves a subquery's scope independently of the enclosing statement, so it reads
    /// the RETURNING list against the inner `SELECT` and emits three spurious "no matching SELECT
    /// column" warnings for SeatRef -- one per component. They are false positives: the row mapper is
    /// generated from the record's component names (`seat_id`, `event_id`, `version`) and is the same
    /// one `expireHolds` already uses.
    @Query("""
           UPDATE reservations SET state = 'cancelled', expires_at = NULL, version = version + 1
           WHERE state = 'confirmed' AND created_at < now() - interval '1 hour'
           AND claim_id NOT IN (SELECT reservation_claim_id FROM bookings WHERE status = 'confirmed')
           RETURNING seat_id, event_id, version""")
    Promise<List<SeatRef>> expireOrphanedConfirmations();
}
